---
collections: []
  # - name: ansible.netcommon
  #   version: 5.1.2
  # - name: ansible.posix
  #   version: 1.5.4
  # - name: ansible.utils
  #   version: 2.10.3
  # - name: ansible.windows
  #   version: 1.14.0

  # - name: community.docker
  #   version: 3.4.8
  # - name: community.general
  #   version: 7.4.0
