---
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

name: ⚒️ CI

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_file: .yamllint

  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          apt install -y -qq ansible-lint git
          git --version
          ansible-lint --version
          ansible-lint -v

  ansible-syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          apt install -y -qq ansible git
          git --version
          ansible-galaxy --version
          ansible-playbook --version
          ansible-playbook --syntax-check --list-tasks playbooks/*.yml
